# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from threading import Thread
from functools import partial


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(255, 250)
        self.pushButton_generate = QtWidgets.QPushButton(Dialog)
        self.pushButton_generate.setGeometry(QtCore.QRect(70, 180, 121, 23))
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 50, 141, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_width = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_width.setObjectName("label_width")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_width)
        self.lineEdit_width = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_width)
        self.label_height = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_height.setObjectName("label_height")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_height)
        self.lineEdit_height = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_height)
        self.label_seed = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_seed.setObjectName("label_seed")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_seed)
        self.lineEdit_seed = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_seed.setObjectName("lineEdit_seed")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_seed)
        self.checkBox_headless = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_headless.setChecked(True)
        self.checkBox_headless.setObjectName("checkBox_headless")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkBox_headless)
        self.checkBox_save = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBox_save.setObjectName("checkBox_save")
        self.checkBox_save.setChecked(True)
        self.checkBox_save.setDisabled(True)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkBox_save)
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(40, 10, 181, 21))
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setScaledContents(False)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")

        self.label_done = QtWidgets.QLabel(Dialog)
        self.label_done.setGeometry(QtCore.QRect(40, 210, 181, 21))
        self.label_done.setTextFormat(QtCore.Qt.AutoText)
        self.label_done.setScaledContents(False)
        self.label_done.setAlignment(QtCore.Qt.AlignCenter)
        self.label_done.setObjectName("label_done")
        self.label_done.setVisible(False)

        self.label_generating = QtWidgets.QLabel(Dialog)
        self.label_generating.setGeometry(QtCore.QRect(40, 210, 181, 21))
        self.label_generating.setTextFormat(QtCore.Qt.AutoText)
        self.label_generating.setScaledContents(False)
        self.label_generating.setAlignment(QtCore.Qt.AlignCenter)
        self.label_generating.setObjectName("label_generating")
        self.label_generating.setVisible(False)

        self.retranslateUi(Dialog)

        self.pushButton_generate.clicked.connect(self.generate_clicked)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Randemon Generator"))
        self.pushButton_generate.setText(_translate("Dialog", "Generate"))
        self.label_width.setText(_translate("Dialog", "width"))
        self.lineEdit_width.setText(_translate("Dialog", "50"))
        self.label_height.setText(_translate("Dialog", "height"))
        self.lineEdit_height.setText(_translate("Dialog", "50"))
        self.label_seed.setText(_translate("Dialog", "seed"))
        self.checkBox_headless.setText(_translate("Dialog", "headless"))
        self.checkBox_save.setText(_translate("Dialog", "save"))
        self.label_title.setText(_translate("Dialog", "Randemon Generator"))
        self.label_done.setText(_translate("Dialog", "Render complete"))
        self.label_generating.setText(_translate("Dialog", "Generating..."))

    def generate_clicked(self):
        comm_str = "python mapGenerator2.py "
        try:
            val = str(int(self.lineEdit_width.text()))
            comm_str += '--w ' + val + " "
        except Exception:
            print('no width')
        try:
            val = str(int(self.lineEdit_height.text()))
            comm_str += '--h ' + val + " "
        except Exception:
            print('no height')

        try:
            val = str(int(self.lineEdit_seed.text()))
            comm_str += '--seed ' + val + " "
        except Exception:
            print('no seed')

        if self.checkBox_headless.isChecked():
            comm_str += "--headless "
        if self.checkBox_save.isChecked():
            comm_str += "--save "
        print(comm_str)

        t = Thread(target=partial(self.runCommand, comm_str))
        t.daemon = True
        t.start()
        return

    def runCommand(self, command):
        self.label_done.setVisible(False)
        self.label_generating.setVisible(True)
        os.system(command)
        self.label_generating.setVisible(False)
        self.label_done.setVisible(True)




class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self)

if __name__ == "__main__":
    app = QApplication(sys.argv)

    window = MainWindow()
    window.show()

    sys.exit(app.exec_())